name: designs
description: Dribbble recreations in Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.1.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts:
  flutter_svg:
  dotted_border:
  smooth_page_indicator:
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/tech_education/
    - assets/design_meetings/